Migrate Extension to React and Typescript
wastadtlander/Youtube-Comment-Translator pull request #19
Opened 2023-11-12 01:46 UTC by quinnha

Migrate Extension to React and Typescript

## Description
Basically just created a react app and loaded existing files in it. translated content.js to ts. also added some boilerplate for for william to use to connect the front end with the backend

Need to refactor in UI changes + folders into react file structure, later pr

i hate git

2023-11-12 22:00 UTC, wastadtlander requested changes

2023-11-12 22:00 UTC, wastadtlander commented on package-lock.json
I was wrong btw we don't gitignore this file.

2023-11-12 22:00 UTC, wastadtlander commented on public/logo192.png
Guessing we need to replace this with a logo eventually?

2023-11-12 22:00 UTC, wastadtlander commented on public/index.html
So this is equivalent to what will be popup.html right?

2023-11-12 22:00 UTC, wastadtlander commented on public/manifest.json
> +  "name": "Chrome React SEO Extension",
Chagne name.

2023-11-12 22:00 UTC, wastadtlander commented on public/manifest.json
> +  "description": "The power of React and TypeScript for building interactive Chrome extensions",
Change description.

2023-11-12 22:00 UTC, wastadtlander commented on public/manifest.json
> +    "default_title": "Open the popup"
Change title to like `Comment Translator`

2023-11-12 22:00 UTC, wastadtlander commented on public/manifest.json
> +  "icons": {
We can probably dump the icons for now.

2023-11-12 22:00 UTC, wastadtlander commented on public/manifest.json
> +      "js": ["./static/js/content.js"]
Line up and fix the alignment of the bracket and brace below.

2023-11-12 22:00 UTC, wastadtlander commented on public/robots.txt
What is this for?

2023-11-12 22:00 UTC, wastadtlander commented on src/App.test.tsx
Can we dump this test for now just to cleanup what we don't need.

2023-11-12 22:00 UTC, wastadtlander commented on src/App.tsx
> +  const getUILanguage = () => {
Wait so is this where the UI stuff would go?

2023-11-12 22:00 UTC, wastadtlander commented on src/chromeServices/DOMEvaluator.ts
> +/**
one line

2023-11-12 22:00 UTC, wastadtlander commented on src/chromeServices/content.ts
> + * Observer to translate new comments on load
one line

2023-11-12 22:00 UTC, wastadtlander commented on src/index.tsx
ok i see this is the parent tsx file that returns html.

2023-11-12 22:00 UTC, wastadtlander commented on src/reportWebVitals.ts
whats this?

2023-11-12 22:14 UTC, quinnha reviewed
done

2023-11-12 22:14 UTC, quinnha commented on package-lock.json
swag

2023-11-12 22:14 UTC, quinnha commented on public/index.html
no, app.tsx will be whats equivalent to popup.html, index.html just mounts the react component - can also link to static assets like icons, fonts, and any external CSS files that are not part of the React component structure

2023-11-12 22:14 UTC, quinnha commented on public/logo192.png
yea i just left it in bc its default, can do whenever we figure out logos and brandings and stuff

2023-11-12 22:14 UTC, quinnha commented on public/manifest.json
> +  "name": "Chrome React SEO Extension",
woopsies

2023-11-12 22:14 UTC, quinnha commented on public/manifest.json
> +  "description": "The power of React and TypeScript for building interactive Chrome extensions",
woopsies (2)

2023-11-12 22:14 UTC, quinnha commented on public/manifest.json
> +  "icons": {
was just placeholder but can remove

2023-11-12 22:14 UTC, quinnha commented on public/robots.txt
autogend, its for the webcrawlers, and lets people google our extension

2023-11-12 22:14 UTC, quinnha commented on src/App.test.tsx
sure, guess we can just add it back later when we figure out testing

2023-11-12 22:14 UTC, quinnha commented on src/App.tsx
> +  const getUILanguage = () => {
in the return statement slightly below is where the UI is rendered, these are just functions -> this one in particular just gets the language of the browser

2023-11-12 22:14 UTC, quinnha commented on src/index.tsx
yea this is where it be rendering

2023-11-12 22:14 UTC, quinnha commented on src/reportWebVitals.ts
see index.tsx

```
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
```

2023-11-13 00:49 UTC, wastadtlander approved these changes

2023-11-13 00:50 UTC, merged